name: 'Manage support request issues'

permissions:
  contents: read
  issues: write

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v5
        with:
          github-token: ${{ github.token }}
          support-label:  "Support request"
          issue-comment: >
            Hi, we only accept **bug reports** on this issue tracker, but this issue looks like a support request.


            Instead of creating an issue, try the following:

            - Check the repository [README and docs](https://github.com/Bedrock-Phanatics/Quark) to see if you can find answers there

            - Ask the community on our [Discord server](https://discord.gg/vrPugybpJF)

          close-issue: true
          lock-issue: false
